defmodule Docuconf.ExportTest do
  use ExUnit.Case, async: true

  @golden Path.expand("golden/sample.cue", __DIR__)

  defp tmp_dir do
    dir = Path.join(System.tmp_dir!(), "docuconf-export-#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    dir
  end

  test "the sample export matches the golden file" do
    out = Docuconf.Test.SampleEnv.export()

    if System.get_env("UPDATE_GOLDEN") == "1", do: File.write!(@golden, out)
    assert out == File.read!(@golden)
  end

  test "export is deterministic and sorted by name" do
    a = Docuconf.Test.SampleEnv.export()
    assert a == Docuconf.Test.SampleEnv.export()
    vars = Regex.scan(~r/^\t\t([A-Z][A-Z0-9_]*): \{/m, a) |> Enum.map(&List.last/1)
    assert vars == Enum.sort(vars)
    assert hd(String.split(a, "\n")) == "// Code generated by docuconf. DO NOT EDIT."
  end

  test "export options set the package and appVersion" do
    out = Docuconf.Test.SampleEnv.export(package: "gw", app_version: "1.2.3")
    assert out =~ "\npackage gw\n"
    assert out =~ ~s(appVersion: "1.2.3")
  end

  test "secret values never reach the contract" do
    out = Docuconf.Test.SampleEnv.export()
    [_, db] = Regex.run(~r/DATABASE_URL: \{(.*?)\n\t\t\}/s, out)
    refute db =~ "default"
  end

  test "mix docuconf.export writes and checks contract.cue" do
    Mix.shell(Mix.Shell.Process)
    on_exit(fn -> Mix.shell(Mix.Shell.IO) end)
    dir = tmp_dir()
    out = Path.join(dir, "contract.cue")
    Mix.Tasks.Docuconf.Export.run(["Docuconf.Test.SampleEnv", "--output", out, "--app-version", "9.9.9"])
    assert File.read!(out) =~ ~s(appVersion: "9.9.9")
    Mix.Tasks.Docuconf.Export.run(["Docuconf.Test.SampleEnv", "--output", out, "--app-version", "9.9.9", "--check"])
    File.write!(out, "stale")

    assert_raise Mix.Error, fn ->
      Mix.Tasks.Docuconf.Export.run(["Docuconf.Test.SampleEnv", "--output", out, "--check"])
    end
  end

  # cue vet -c against the meta-schema. The meta-schema lives in docuconf-go
  # (spec/cue); DOCUCONF_SPEC_CUE points at it, else a sibling checkout is
  # used. Skipped when cue or the spec is absent, unless DOCUCONF_REQUIRE_VET=1.
  describe "cue vet" do
    setup do
      spec = System.get_env("DOCUCONF_SPEC_CUE") || Path.expand("../../docuconf-go/spec/cue", __DIR__)
      cue = System.find_executable("cue") || existing(Path.expand("~/go/bin/cue"))
      ok? = cue != nil and File.dir?(Path.join(spec, "contract"))

      cond do
        ok? -> {:ok, cue: cue, spec: spec}
        System.get_env("DOCUCONF_REQUIRE_VET") == "1" -> flunk("cue or the meta-schema (#{spec}) is missing")
        true -> :ok
      end
    end

    defp existing(path), do: if(File.exists?(path), do: path)

    test "the sample contract passes cue vet -c", ctx do
      if ctx[:cue] do
        assert {"", 0} == vet(ctx, Docuconf.Test.SampleEnv.export())
      else
        IO.puts(:stderr, "skipping cue vet: cue or the docuconf meta-schema is not available")
      end
    end

    test "a minimal contract with no files passes cue vet -c", ctx do
      if ctx[:cue] do
        [{mod, _}] =
          Code.compile_string("""
          defmodule Docuconf.ExportTest.Minimal do
            use Docuconf, name: "minimal"
            env :port, :integer, description: "HTTP listen port", default: 4000
          end
          """)

        assert {"", 0} == vet(ctx, mod.export())
      end
    end

    defp vet(%{cue: cue, spec: spec}, contract) do
      dir = tmp_dir()
      File.cp_r!(Path.join(spec, "cue.mod"), Path.join(dir, "cue.mod"))
      File.cp_r!(Path.join(spec, "contract"), Path.join(dir, "contract"))
      File.mkdir_p!(Path.join(dir, "svc"))
      File.write!(Path.join(dir, "svc/contract.cue"), contract)
      System.cmd(cue, ["vet", "-c", "./svc"], cd: dir, stderr_to_stdout: true)
    end
  end
end
