defmodule Docuconf.ExportTest do
  use ExUnit.Case, async: true

  @golden Path.expand("golden/sample.cue", __DIR__)

  defp tmp_dir do
    dir = Path.join(System.tmp_dir!(), "docuconf-export-#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    dir
  end

  # metadata.generator.version is the package version, which every release PR
  # bumps, so comparisons with the committed golden file ignore its value.
  defp without_generator_version(cue) do
    Regex.replace(
      ~r/(generator:\s*\{[^{}]*?\bversion:\s*)"[^"]*"/,
      cue,
      ~s(\\1"<generator-version>")
    )
  end

  test "the sample export matches the golden file" do
    out = Docuconf.Test.SampleEnv.export()

    if System.get_env("UPDATE_GOLDEN") == "1", do: File.write!(@golden, out)
    assert without_generator_version(out) == without_generator_version(File.read!(@golden))
  end

  test "the golden comparison ignores only the generator version" do
    out = Docuconf.Test.SampleEnv.export()
    bumped = Regex.replace(~r/(\bversion:\s*)"[^"]*"/, out, ~s(\\1"99.0.0"), global: false)
    assert bumped != out
    assert without_generator_version(bumped) == without_generator_version(out)

    refute without_generator_version(String.replace(out, ~s("elixir"), ~s("erlang"))) ==
             without_generator_version(out)
  end

  test "export is deterministic and sorted by name" do
    a = Docuconf.Test.SampleEnv.export()
    assert a == Docuconf.Test.SampleEnv.export()
    vars = Regex.scan(~r/^\t\t([A-Z][A-Z0-9_]*): \{/m, a) |> Enum.map(&List.last/1)
    assert vars == Enum.sort(vars)
    assert hd(String.split(a, "\n")) == "// Code generated by docuconf. DO NOT EDIT."
  end

  test "export options set the package and appVersion" do
    out = Docuconf.Test.SampleEnv.export(package: "gw", app_version: "1.2.3")
    assert out =~ "\npackage gw\n"
    assert out =~ ~s(appVersion: "1.2.3")
  end

  test "secret values never reach the contract" do
    out = Docuconf.Test.SampleEnv.export()
    [_, db] = Regex.run(~r/DATABASE_URL: \{(.*?)\n\t\t\}/s, out)
    refute db =~ "default"
  end

  test "mix docuconf.export writes and checks contract.cue" do
    Mix.shell(Mix.Shell.Process)
    on_exit(fn -> Mix.shell(Mix.Shell.IO) end)
    dir = tmp_dir()
    out = Path.join(dir, "contract.cue")

    Mix.Tasks.Docuconf.Export.run([
      "Docuconf.Test.SampleEnv",
      "--output",
      out,
      "--app-version",
      "9.9.9"
    ])

    assert File.read!(out) =~ ~s(appVersion: "9.9.9")

    Mix.Tasks.Docuconf.Export.run([
      "Docuconf.Test.SampleEnv",
      "--output",
      out,
      "--app-version",
      "9.9.9",
      "--check"
    ])

    # A version bump is not a contract change.
    Mix.Tasks.Docuconf.Export.run([
      "Docuconf.Test.SampleEnv",
      "--output",
      out,
      "--app-version",
      "10.0.0",
      "--check"
    ])

    File.write!(out, String.replace(File.read!(out), ~s(default: 8080), ~s(default: 8081)))

    e =
      assert_raise Mix.Error, fn ->
        Mix.Tasks.Docuconf.Export.run(["Docuconf.Test.SampleEnv", "--output", out, "--check"])
      end

    assert e.message =~
             "is out of date; run: mix docuconf.export Docuconf.Test.SampleEnv --output #{out}"

    assert e.message =~ "-\t\t\tdefault: 8081"
    assert e.message =~ "+\t\t\tdefault: 8080"
  end

  test "mix docuconf.export -o - writes only the contract to stdout" do
    Mix.shell(Mix.Shell.Process)
    on_exit(fn -> Mix.shell(Mix.Shell.IO) end)

    out =
      ExUnit.CaptureIO.capture_io(fn ->
        Mix.Tasks.Docuconf.Export.run(["Docuconf.Test.SampleEnv", "-o", "-"])
      end)

    assert out == Docuconf.Test.SampleEnv.export(app_version: Mix.Project.config()[:version])
    # The shell is restored after the quiet compile.
    assert Mix.shell() == Mix.Shell.Process
  end

  # cue vet -c against the meta-schema. The meta-schema lives in docuconf-go
  # (spec/cue); DOCUCONF_SPEC_CUE points at it, else a sibling checkout is
  # used. Skipped when cue or the spec is absent, unless DOCUCONF_REQUIRE_VET=1.
  describe "cue vet" do
    setup do
      spec =
        System.get_env("DOCUCONF_SPEC_CUE") || Path.expand("../../docuconf-go/spec/cue", __DIR__)

      cue = System.find_executable("cue") || existing(Path.expand("~/go/bin/cue"))
      ok? = cue != nil and File.dir?(Path.join(spec, "contract"))

      cond do
        ok? ->
          {:ok, cue: cue, spec: spec}

        System.get_env("DOCUCONF_REQUIRE_VET") == "1" ->
          flunk("cue or the meta-schema (#{spec}) is missing")

        true ->
          :ok
      end
    end

    defp existing(path), do: if(File.exists?(path), do: path)

    test "the sample contract passes cue vet -c", ctx do
      if ctx[:cue] do
        assert {"", 0} == vet(ctx, Docuconf.Test.SampleEnv.export())
      else
        IO.puts(:stderr, "skipping cue vet: cue or the docuconf meta-schema is not available")
      end
    end

    test "a minimal contract with no files passes cue vet -c", ctx do
      if ctx[:cue] do
        [{mod, _}] =
          Code.compile_string("""
          defmodule Docuconf.ExportTest.Minimal do
            use Docuconf, name: "minimal"
            env :port, :integer, description: "HTTP listen port", default: 4000
          end
          """)

        assert {"", 0} == vet(ctx, mod.export())
      end
    end

    test "every list and duration encoding passes cue vet -c", ctx do
      if ctx[:cue] do
        [{mod, _}] =
          Code.compile_string("""
          defmodule Docuconf.ExportTest.Encodings do
            use Docuconf, name: "encodings"
            env :a, {:list, :string}, description: "Indexed list", encoding: :indexed
            env :b, {:list, :integer}, description: "JSON list", encoding: :json, item_min: 0
            env :c, {:list, :string}, description: "CSV list", separator: ";"
            env :d, :duration, description: "ISO duration", encoding: :iso8601
            env :e, :duration, description: "Seconds duration", encoding: :seconds
            env :f, :duration, description: "TimeSpan duration", encoding: :timespan
          end
          """)

        contract = mod.export()
        assert contract =~ ~s(encoding: "indexed")
        refute contract =~ ~r/encoding: "json"\n\t*separator/
        assert {"", 0} == vet(ctx, contract)
      end
    end

    defp vet(%{cue: cue, spec: spec}, contract) do
      dir = tmp_dir()
      File.cp_r!(Path.join(spec, "cue.mod"), Path.join(dir, "cue.mod"))
      File.cp_r!(Path.join(spec, "contract"), Path.join(dir, "contract"))
      File.mkdir_p!(Path.join(dir, "svc"))
      File.write!(Path.join(dir, "svc/contract.cue"), contract)
      System.cmd(cue, ["vet", "-c", "./svc"], cd: dir, stderr_to_stdout: true)
    end
  end
end
