// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "orders"
		appVersion: "1.4.0"
		generator: {
			language: "elixir"
			sdk: "docuconf"
			version: "0.1.0"
		}
	}
	vars: {
		CHECKOUT_TIMEOUT: {
			type: "duration"
			description: "Checkout request timeout"
			encoding: "go"
			default: "15s"
		}
		DATABASE_URL: {
			type: "url"
			description: "Primary Postgres connection string"
			required: true
			secret: true
			schemes: ["postgres", "ecto"]
		}
		LOG_LEVEL: {
			type: "enum"
			description: "Minimum log level"
			values: ["debug", "info", "warning", "error"]
			default: "info"
		}
		POOL_SIZE: {
			type: "int"
			description: "Database connection pool size"
			min: 1
			default: 10
		}
		PORT: {
			type: "int"
			description: "HTTP listen port"
			min: 1
			max: 65535
			default: 4000
		}
	}
	files: {
		pricing: {
			type: "config"
			format: "json"
			description: "Pricing rules: currency and discount tiers"
			required: true
			path: "/etc/orders/pricing/pricing.json"
			schema: {
				additionalProperties: false
				properties: {
					currency: {
						pattern: "^[A-Z]{3}$"
						type: "string"
					}
					tiers: {
						items: {
							additionalProperties: false
							properties: {
								min_total: {
									minimum: 1
									type: "integer"
								}
								percent: {
									maximum: 100
									minimum: 0
									type: "integer"
								}
							}
							required: ["min_total", "percent"]
							type: "object"
						}
						type: "array"
					}
				}
				required: ["currency", "tiers"]
				type: "object"
			}
		}
		"serving-tls": {
			type: "tls"
			description: "Certificate the API serves HTTPS with"
			secret: true
			path: "/etc/orders/tls"
			dnsNames: ["orders.internal"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
		}
	}
}
