defmodule Docuconf.CUE do
  @moduledoc """
  Writes a declaration as a `contract.cue` document (SPEC §4): plain data
  unified with `contract.#Contract`, with variables and file inputs sorted
  by name so the output is deterministic.
  """

  alias Docuconf.{Declaration, Duration, FileInput, Var}

  @sdk "docuconf"
  @version Mix.Project.config()[:version]

  @doc """
  Renders the contract. Options: `:package` (CUE package name; default the
  service name with `-` replaced by `_`) and `:app_version`.
  """
  @spec export(Declaration.t(), keyword()) :: String.t()
  def export(%Declaration{} = d, opts \\ []) do
    package = Keyword.get_lazy(opts, :package, fn -> String.replace(d.name, "-", "_") end)
    app_version = Keyword.get(opts, :app_version, d.app_version)

    metadata =
      [{"name", d.name}] ++
        if(app_version, do: [{"appVersion", to_string(app_version)}], else: []) ++
        [{"generator", {:struct, [{"language", "elixir"}, {"sdk", @sdk}, {"version", @version}]}}]

    body =
      [
        {"apiVersion", "docuconf.dev/v1alpha1"},
        {"kind", "ConfigContract"},
        {"metadata", {:struct, metadata}},
        {"vars", {:struct, Enum.map(d.vars, &{&1.name, {:struct, var_fields(&1)}})}}
      ] ++
        if d.files == [],
          do: [],
          else: [{"files", {:struct, Enum.map(d.files, &{&1.name, {:struct, file_fields(&1)}})}}]

    IO.iodata_to_binary([
      "// Code generated by docuconf. DO NOT EDIT.\n",
      "package ",
      package,
      "\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & ",
      value({:struct, body}, 0),
      "\n"
    ])
  end

  @doc false
  def var_fields(%Var{} = v) do
    [
      {"type", v.type},
      {"description", v.description},
      v.required && {"required", true},
      v.secret && {"secret", true},
      v.group && {"group", v.group},
      v.examples && {"examples", v.examples},
      v.config_key && {"configKey", v.config_key}
    ] ++
      type_fields(v) ++
      [
        v.has_default && not v.secret && {"default", export_default(v)},
        v.deprecated && {"deprecated", deprecated(v.deprecated)}
      ]
    |> Enum.filter(& &1)
  end

  defp type_fields(%Var{type: "string"} = v),
    do: [v.min_length && {"minLength", v.min_length}, v.max_length && {"maxLength", v.max_length}, v.pattern && {"pattern", v.pattern}]

  defp type_fields(%Var{type: t} = v) when t in ["int", "float"],
    do: [v.min != nil && {"min", v.min}, v.max != nil && {"max", v.max}]

  defp type_fields(%Var{type: "duration"} = v),
    do: [{"encoding", "go"}, v.min && {"min", Duration.format(v.min)}, v.max && {"max", Duration.format(v.max)}]

  defp type_fields(%Var{type: "url"} = v), do: [v.schemes && {"schemes", v.schemes}]
  defp type_fields(%Var{type: "enum"} = v), do: [{"values", v.values}]

  defp type_fields(%Var{type: "list"} = v),
    do: [
      {"items", v.items},
      {"encoding", "csv"},
      {"separator", v.separator},
      v.min_items && {"minItems", v.min_items},
      v.max_items && {"maxItems", v.max_items}
    ]

  defp type_fields(%Var{type: "json"} = v), do: [v.schema && {"schema", v.schema}]
  defp type_fields(_), do: []

  defp export_default(%Var{type: "duration", default: ns}), do: Duration.format(ns)
  defp export_default(%Var{default: d}), do: d

  defp deprecated(%{message: m} = d) do
    {:struct, Enum.filter([{"message", m}, d[:replaced_by] && {"replacedBy", to_string(d[:replaced_by])}], & &1)}
  end

  @doc false
  def file_fields(%FileInput{} = f) do
    [
      {"type", f.type},
      f.type in ["config", "keystore"] && {"format", f.format},
      {"description", f.description},
      f.required && {"required", true},
      f.secret && {"secret", true},
      f.group && {"group", f.group},
      {"path", f.path},
      f.path_env && {"pathEnv", f.path_env},
      f.reload != "restart" && {"reload", f.reload},
      f.max_size && {"maxSize", f.max_size}
    ] ++
      file_type_fields(f) ++
      [f.deprecated && {"deprecated", deprecated(f.deprecated)}]
    |> Enum.filter(& &1)
  end

  defp file_type_fields(%FileInput{type: "config"} = f), do: [f.schema && {"schema", f.schema}]

  defp file_type_fields(%FileInput{type: "tls"} = f),
    do: [
      f.dns_names && {"dnsNames", f.dns_names},
      f.key_algorithms && {"keyAlgorithms", f.key_algorithms},
      f.min_remaining && {"minRemaining", Duration.format(f.min_remaining)},
      f.require_ca && {"requireCA", true}
    ]

  defp file_type_fields(%FileInput{type: "caBundle"} = f),
    do: [f.min_certificates != 1 && {"minCertificates", f.min_certificates}]

  defp file_type_fields(%FileInput{type: "keystore"} = f), do: [f.password_var && {"passwordVar", f.password_var}]

  defp file_type_fields(%FileInput{type: "text"} = f),
    do: [f.pattern && {"pattern", f.pattern}, f.min_length && {"minLength", f.min_length}, f.max_length && {"maxLength", f.max_length}]

  defp file_type_fields(_), do: []

  # ---- CUE data encoding ---------------------------------------------------

  @doc false
  def value({:struct, []}, _ind), do: "{}"

  def value({:struct, fields}, ind) do
    pad = String.duplicate("\t", ind + 1)
    inner = Enum.map(fields, fn {k, v} -> [pad, label(k), ": ", value(v, ind + 1), "\n"] end)
    ["{\n", inner, String.duplicate("\t", ind), "}"]
  end

  def value(%{} = m, ind), do: value({:struct, m |> Enum.map(fn {k, v} -> {to_string(k), v} end) |> Enum.sort()}, ind)

  def value([], _ind), do: "[]"

  def value(list, ind) when is_list(list) do
    if Enum.all?(list, &scalar?/1) do
      ["[", Enum.intersperse(Enum.map(list, &value(&1, ind)), ", "), "]"]
    else
      pad = String.duplicate("\t", ind + 1)
      ["[\n", Enum.map(list, &[pad, value(&1, ind + 1), ",\n"]), String.duplicate("\t", ind), "]"]
    end
  end

  def value(s, _ind) when is_binary(s), do: string(s)
  def value(true, _), do: "true"
  def value(false, _), do: "false"
  def value(nil, _), do: "null"
  def value(i, _) when is_integer(i), do: Integer.to_string(i)
  def value(f, _) when is_float(f), do: float(f)
  def value(a, _) when is_atom(a), do: string(Atom.to_string(a))

  defp scalar?(v), do: not (is_list(v) or is_map(v) or match?({:struct, _}, v))

  # JSON string syntax is valid CUE string syntax, except that CUE reads
  # "\(" as interpolation, so a literal backslash must stay escaped (JSON
  # always escapes it).
  defp string(s), do: JSON.encode!(s)

  defp float(f) do
    # Shortest round-trip form; CUE wants a digit after the point.
    s = Float.to_string(f)
    if String.contains?(s, "e") and not String.contains?(s, "."), do: String.replace(s, "e", ".0e"), else: s
  end

  @keywords ~w(package import for in if let true false null _ div mod quo rem)

  defp label(k) do
    if Regex.match?(~r/^[A-Za-z][A-Za-z0-9_]*\z/, k) and k not in @keywords, do: k, else: string(k)
  end
end
